"""Build the JavaScript data used by the biomacromolecule puzzle."""

import json
from pathlib import Path

import yaml


CATEGORY_MAP = {
	"proteins": "Protein",
	"lipids": "Lipid",
	"carbohydrates": "Carbohydrate",
	"nucleic acids": "Nucleic Acid",
}

SUBCATEGORY_RENAMES = {
	"glycolysis": "glycolysis intermediates",
	"similar to glycolysis": "glycolysis intermediates",
}


def build_abbreviation_index(pubchem_data: dict[str, object]) -> dict[str, dict[str, object]]:
	"""Build a case-insensitive abbreviation-to-record index."""
	index: dict[str, dict[str, object]] = {}
	for record in pubchem_data.get("cid_to_data", {}).values():
		abbreviation = record.get("Abbreviation", "")
		if abbreviation:
			index[abbreviation.lower().strip()] = record
	return index


def _default_paths(repo_root: Path) -> tuple[Path, Path, Path]:
	biology_problems_root = repo_root.parent / "biology-problems"
	macro_path = (
		biology_problems_root
		/ "problems"
		/ "biochemistry-problems"
		/ "PUBCHEM"
		/ "MACROMOLECULE_CATEGORIZE"
		/ "macromolecules.yml"
	)
	pubchem_path = biology_problems_root / "data" / "pubchem_molecules_data.yml"
	output_path = repo_root / "site_docs" / "assets" / "scripts" / "biomacromolecule_data.js"
	return macro_path, pubchem_path, output_path


def write_js(
	repo_root: str | Path,
	macromolecule_path: str | Path | None = None,
	pubchem_path: str | Path | None = None,
	output_path: str | Path | None = None,
) -> int:
	"""Merge source YAML files and write deterministic JavaScript data."""
	root = Path(repo_root)
	default_macro, default_pubchem, default_output = _default_paths(root)
	macro_file = Path(macromolecule_path) if macromolecule_path else default_macro
	pubchem_file = Path(pubchem_path) if pubchem_path else default_pubchem
	output_file = Path(output_path) if output_path else default_output
	print(f"Loading {macro_file}")
	with macro_file.open("r") as file_handle:
		macro_data = yaml.safe_load(file_handle)
	print(f"Loading {pubchem_file}")
	with pubchem_file.open("r") as file_handle:
		pubchem_data = yaml.safe_load(file_handle)
	abbreviation_index = build_abbreviation_index(pubchem_data)
	print(f"PubChem index: {len(abbreviation_index)} entries")
	molecules: list[dict[str, object]] = []
	subcategories: dict[str, list[str]] = {}
	matched = 0
	skipped = 0
	skipped_names: list[str] = []
	for category_key, category_name in CATEGORY_MAP.items():
		category_data = macro_data.get(category_key, {})
		if not category_data:
			print(f"  WARNING: no data for category key '{category_key}'")
			continue
		category_subcategories: set[str] = set()
		for subcategory_key, molecule_list in category_data.items():
			if not molecule_list:
				continue
			subcategory_name = SUBCATEGORY_RENAMES.get(subcategory_key, subcategory_key)
			category_subcategories.add(subcategory_name)
			for molecule_name in molecule_list:
				if not molecule_name:
					continue
				name = str(molecule_name).strip()
				record = abbreviation_index.get(name.lower())
				if not record:
					skipped += 1
					skipped_names.append(f"  [{category_name}] {name}")
					continue
				smiles = record.get("SMILES", "")
				if not smiles:
					skipped += 1
					skipped_names.append(f"  [{category_name}] {name} (no SMILES)")
					continue
				molecules.append({
					"name": name,
					"smiles": smiles,
					"formula": record.get("Molecular formula", ""),
					"weight": record.get("Molecular weight", 0),
					"category": category_name,
					"subcategory": subcategory_name,
				})
				matched += 1
		subcategories[category_name] = sorted(category_subcategories)
	molecules.sort(key=lambda molecule: molecule["name"].lower())
	categories = sorted(CATEGORY_MAP.values())
	print(f"\nMatched: {matched}, Skipped: {skipped}")
	if skipped_names:
		print("Skipped molecules:")
		for name in skipped_names:
			print(name)
	data_obj = {
		"categories": categories,
		"subcategories": subcategories,
		"molecules": molecules,
	}
	js_content = (
		"/* Auto-generated by site_maint.py - DO NOT EDIT */\n"
		"window.BiomacromoleculeData = "
		+ json.dumps(data_obj, indent=1, ensure_ascii=False)
		+ ";\n"
	)
	output_file.parent.mkdir(parents=True, exist_ok=True)
	output_file.write_text(js_content)
	file_size = output_file.stat().st_size
	print(f"\nWrote {output_file}")
	print(f"  {matched} molecules, {file_size / 1024:.1f} KB")
	print(f"  Categories: {categories}")
	for category, subcategory_names in sorted(subcategories.items()):
		print(f"  {category}: {subcategory_names}")
	return 0
