"""Render the homepage from a generated collection snapshot."""

import html


ACTIVITY = {
	"new": {
		"title": "Latest additions", "route": "latest_additions",
		"description": "New to the site: question families added to the collection, newest first.",
		"date_label": "Added",
		"history": "Dates reflect the first recorded inclusion in the collection. "
			"The original collection and additions with unknown dates are not listed.",
		"empty": "No dated additions are available yet.",
	},
	"updated": {
		"title": "Recently updated", "route": "recently_updated",
		"description": "Question families with verified content revisions, newest first.",
		"date_label": "Revised",
		"history": "Dates reflect source content revisions incorporated into generated question banks. "
			"Older banks without verified revision dates are not listed. "
			"This list grows as revised banks are regenerated.",
		"empty": "No verified updates are available yet. You can still browse all question sets.",
	},
}


COURSE_COPY = {
	"biochemistry": ("From molecular structure to metabolism.",
		"Biomolecules, proteins, enzymes, and energy."),
	"genetics": ("From inheritance patterns to gene mapping.",
		"Mendelian genetics, pedigrees, linkage, and populations."),
	"molecular_biology": ("DNA, RNA, gene expression, and molecular techniques.", ""),
	"biostatistics": ("Data interpretation, probability, and statistical tests.", ""),
	"laboratory": ("Measurements, solutions, dilutions, and lab methods.", ""),
	"biotechnology": ("Genomics, protein technology, medicine, and bioethics.", ""),
	"other": ("Cell biology, biophysics, and interdisciplinary problems.", ""),
}


#============================================
def escape(value: str) -> str:
	"""Encode text and attributes at the HTML boundary (ASVS 1.2.1)."""
	return html.escape(value, quote=True)


#============================================
def course(subject: dict, featured: bool = False) -> str:
	"""Make the whole subject card one accessible link."""
	key = subject["key"]
	description, detail = COURSE_COPY.get(key, ("Browse this subject.", ""))
	style = "home-course featured" if featured else "home-course"
	text = f'<a class="{style} subject-{escape(key)}" href="{escape(subject["url"])}">'
	icon = escape(subject["icon"]).encode("ascii", "xmlcharrefreplace").decode("ascii")
	text += f'<span class="home-course-icon" aria-hidden="true">{icon}</span>'
	if featured:
		text += '<span class="home-tag">Complete course</span>'
	text += f'<h3>{escape(subject["title"])} <span aria-hidden="true">&rarr;</span></h3>'
	text += f'<p>{escape(description)}</p>'
	if featured:
		text += f'<p class="home-detail">{escape(detail)}</p>'
	text += f'<span class="home-count"><b>{subject["sets"]:,}</b> question sets'
	text += f' <span aria-hidden="true">&middot;</span> {subject["topics"]} topics</span></a>'
	return text


#============================================
def activity(key: str, rows: list) -> str:
	"""Render a compact dated list, with an intentional empty state."""
	details = ACTIVITY[key]
	text = f'<section class="home-panel"><h3>{details["title"]}</h3>'
	if not rows:
		text += f'<p class="home-empty">{details["empty"]}</p>'
	else:
		text += '<ul class="home-activity">'
		for row in rows[:5]:
			text += f'<li><a href="{escape(row["url"])}">{escape(row["name"])}</a>'
			text += f'<span>{escape(row["subject"])} <span aria-hidden="true">&middot;</span> '
			text += f'<time datetime="{escape(row["date"])}">{escape(row["date"])}</time></span></li>'
		text += '</ul>'
	text += f'<a class="home-view-all" href="{details["route"]}/" '
	text += f'aria-label="View all {details["title"].lower()}">View all &rarr;</a></section>'
	return text


#============================================
def activity_page(key: str, rows: list[dict]) -> str:
	"""Render the complete dated collection with the homepage's history semantics."""
	details = ACTIVITY[key]
	text = f'---\ntitle: {details["title"]}\nhide:\n  - toc\n---\n\n'
	text += '<!-- Generated by build_site.py. Edit homepage_render.py, not this file. -->\n'
	text += '<div class="home activity-page" data-selftest-personalization="off">'
	text += '<nav class="activity-nav" aria-label="Collection activity">'
	text += '<a href="../">Home</a>'
	for other_key, other in ACTIVITY.items():
		current = ' aria-current="page"' if other_key == key else ''
		text += f'<a href="../{other["route"]}/"{current}>{other["title"]}</a>'
	text += '</nav><header class="home-panel">'
	text += f'<h1>{details["title"]}</h1><p>{details["description"]}</p>'
	text += f'<p class="activity-history">{details["history"]}</p>'
	text += '<p class="activity-history">Each question family appears once, with format variants '
	text += 'grouped together. Open a collection to preview questions and download a bank.</p>'
	text += '<a class="home-view-all" href="../question_finder/">Find question sets &rarr;</a></header>'
	if not rows:
		text += f'<p class="activity-empty">{details["empty"]}</p>'
	else:
		text += '<ol class="activity-list">'
		for row in rows:
			text += '<li><article class="home-panel">'
			text += f'<p class="activity-date">{details["date_label"]} '
			text += f'<time datetime="{escape(row["date"])}">{escape(row["date"])}</time></p>'
			text += f'<h2><a href="../{escape(row["url"])}">{escape(row["name"])}</a></h2>'
			text += f'<p class="activity-context">{escape(row["subject"])} &middot; {escape(row["topic"])}</p>'
			text += '</article></li>'
		text += '</ol>'
	text += '</div>\n'
	return text


#============================================
def chart(subjects: list) -> str:
	"""Keep values readable without color, hover, JavaScript, or chart libraries."""
	maximum = max((subject["sets"] for subject in subjects), default=0) or 1
	text = '<section class="home-panel"><h3>Question sets by subject</h3><ul class="home-chart">'
	for subject in subjects:
		width = subject["sets"] / maximum * 100
		text += f'<li class="subject-{escape(subject["key"])}">'
		text += f'<a href="{escape(subject["url"])}"><span>{escape(subject["title"])}</span>'
		text += f'<b>{subject["sets"]:,}</b></a>'
		text += f'<span class="home-bar" aria-hidden="true"><i style="width:{width:.2f}%"></i></span></li>'
	text += '</ul><p class="home-footnote">Counts include each subject listing. '
	text += 'Format variants count as separate sets.</p></section>'
	return text


#============================================
def render(snapshot: dict) -> str:
	"""Compose the static teaching showcase; existing routes own all interactions."""
	totals = snapshot["totals"]
	subjects = {subject["key"]: subject for subject in snapshot["subjects"]}
	text = '<!-- Generated by build_site.py. Edit homepage_render.py, not this file. -->\n'
	text += '<div class="home" data-selftest-personalization="off">'
	text += '<section class="home-hero" aria-labelledby="home-title"><div>'
	text += '<p class="home-eyebrow">Free &amp; open teaching resources</p>'
	text += '<h1 id="home-title">Biology Problems</h1>'
	text += '<p>Preview question sets for your course. Download for Blackboard or Canvas.</p>'
	text += '<div class="home-actions"><a class="home-primary" href="question_finder/">'
	text += '<i class="fa fa-sitemap" aria-hidden="true"></i> Find question sets &rarr;</a>'
	text += '<a href="sitemap/">Browse all questions</a></div>'
	text += '<p class="home-filter-hint">Filter by subject, topic, and question type.</p></div>'
	text += '<div class="home-stats" aria-label="Collection statistics">'
	text += f'<strong>{totals["sets"]:,}</strong><span>question sets</span><div>'
	text += f'<b>{totals["subjects"]}</b> subjects <span aria-hidden="true">&middot;</span> '
	text += f'<b>{totals["topics"]}</b> topics</div></div></section>'
	text += '<section aria-labelledby="home-courses"><div class="home-section-heading">'
	text += '<h2 id="home-courses">Two complete courses</h2>'
	text += '<p>Developed with grant support</p></div><div class="home-featured">'
	for key in ("biochemistry", "genetics"):
		if key in subjects:
			text += course(subjects[key], True)
	text += '</div></section><section aria-labelledby="home-additional">'
	text += '<div class="home-section-heading"><h2 id="home-additional">Additional subjects</h2>'
	text += '<p>Selected question collections</p></div><div class="home-additional">'
	for key in subjects:
		if key not in ("biochemistry", "genetics", "other"):
			text += course(subjects[key])
	text += '</div>'
	if "other" in subjects:
		text += '<p class="home-more subject-other">Also explore: <a href="other/topic01/">Cell Biology</a>'
		text += ' <span aria-hidden="true">&middot;</span> <a href="other/topic02/">Biophysics</a>'
		text += f' <span class="home-muted">({subjects["other"]["sets"]} question sets)</span></p>'
	text += '</section><section aria-labelledby="home-collection">'
	text += '<div class="home-section-heading"><h2 id="home-collection">Explore the collection</h2>'
	text += '<a href="question_finder/">Search &amp; filter &rarr;</a></div><div class="home-overview">'
	text += chart(snapshot["subjects"])
	text += activity("new", snapshot["new"])
	text += activity("updated", snapshot["updated"])
	text += '</div></section><section class="home-example" aria-labelledby="home-example-title">'
	text += '<a class="home-example-image" href="genetics/topic05/#inheritance-patterns-from-pedigrees-medium">'
	text += '<img src="assets/images/homepage_pedigree.png" width="409" height="260" loading="lazy" '
	text += 'alt="An actual four-generation pedigree question, with affected individuals shaded blue and unaffected individuals unfilled."></a>'
	text += '<div><p class="home-eyebrow">Real problems. Ready to teach.</p>'
	text += '<h2 id="home-example-title">Find. Preview. Teach.</h2>'
	text += '<p>Interpret a pedigree, try the self-test, '
	text += 'and download the question bank for your course.</p>'
	text += '<a href="genetics/topic05/#inheritance-patterns-from-pedigrees-medium">Try this inheritance problem &rarr;</a>'
	text += '<p class="home-tutorials">Import guides: <a href="tutorials/bbq_tutorial/">Blackboard Learn</a>'
	text += ' <a href="tutorials/bbq_ultra_tutorial/">Blackboard Ultra</a>'
	text += ' <a href="tutorials/canvas_tutorial/">Canvas</a></p></div></section>'
	text += '<section aria-labelledby="home-puzzles"><div class="home-section-heading">'
	text += '<h2 id="home-puzzles">A little biology, every day</h2>'
	text += '<a href="daily_puzzles/">Daily puzzles &rarr;</a></div><div class="home-puzzles">'
	for name, route, description in (
		("Peptidyle", "peptidyle", "Decode a peptide sequence."),
		("Deletion mutants", "deletion_mutants", "Piece together a gene map."),
		("Mutant screen", "mutant_screen", "Follow a metabolic pathway."),
		("Biomacromolecules", "biomacromolecule", "Recognize molecular structures."),
	):
		text += f'<a href="daily_puzzles/{route}/"><b>{name}</b><span>{description}</span></a>'
	text += '</div></section><footer class="home-footer">'
	text += '<span>Created by <a href="author/">Dr. Neil Voss</a> at Roosevelt University.</span>'
	text += '<span><a href="license/">CC BY 4.0</a> &middot; '
	text += '<a href="tutorials/">All tutorials</a> &middot; <a href="progress/">Self-test progress</a></span>'
	text += '</footer></div>\n'
	return text
