#!/usr/bin/env python3
"""Build biomacromolecule_data.js from YAML source files.

Merges macromolecules.yml (category -> subcategory -> molecule names)
with pubchem_molecules_data.yml (CID-keyed records with SMILES, formula, weight)
to produce a single JS data file for the biomacromolecule daily puzzle.
"""

import json
import os
import sys

import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
BIOLOGY_PROBLEMS_ROOT = os.path.join(os.path.dirname(PROJECT_ROOT), "biology-problems")

MACROMOLECULE_YML = os.path.join(
    BIOLOGY_PROBLEMS_ROOT,
    "problems", "biochemistry-problems", "PUBCHEM",
    "MACROMOLECULE_CATEGORIZE", "macromolecules.yml",
)
PUBCHEM_YML = os.path.join(
    BIOLOGY_PROBLEMS_ROOT,
    "data", "pubchem_molecules_data.yml",
)
OUTPUT_JS = os.path.join(
    PROJECT_ROOT,
    "site_docs", "assets", "scripts", "biomacromolecule_data.js",
)

# ---------------------------------------------------------------------------
# Category key mapping
# ---------------------------------------------------------------------------
CATEGORY_MAP = {
    "proteins": "Protein",
    "lipids": "Lipid",
    "carbohydrates": "Carbohydrate",
    "nucleic acids": "Nucleic Acid",
}

SUBCATEGORY_RENAMES = {
    "glycolysis": "glycolysis intermediates",
    "similar to glycolysis": "glycolysis intermediates",
}


def build_abbreviation_index(pubchem_data):
    """Build a case-insensitive index from Abbreviation -> record."""
    index = {}
    cid_data = pubchem_data.get("cid_to_data", {})
    for _cid, record in cid_data.items():
        abbrev = record.get("Abbreviation", "")
        if abbrev:
            index[abbrev.lower().strip()] = record
    return index


def main():
    # Load source YAML files
    print(f"Loading {MACROMOLECULE_YML}")
    with open(MACROMOLECULE_YML, "r") as fh:
        macro_data = yaml.safe_load(fh)

    print(f"Loading {PUBCHEM_YML}")
    with open(PUBCHEM_YML, "r") as fh:
        pubchem_data = yaml.safe_load(fh)

    abbrev_index = build_abbreviation_index(pubchem_data)
    print(f"PubChem index: {len(abbrev_index)} entries")

    molecules = []
    subcategories = {}
    matched = 0
    skipped = 0
    skipped_names = []

    for cat_key, category_name in CATEGORY_MAP.items():
        cat_data = macro_data.get(cat_key, {})
        if not cat_data:
            print(f"  WARNING: no data for category key '{cat_key}'")
            continue

        cat_subcats = set()

        for subcat_key, mol_list in cat_data.items():
            if not mol_list:
                continue

            # Apply subcategory rename
            subcat_display = SUBCATEGORY_RENAMES.get(subcat_key, subcat_key)
            cat_subcats.add(subcat_display)

            for mol_name in mol_list:
                if not mol_name:
                    continue
                mol_name_str = str(mol_name).strip()
                lookup_key = mol_name_str.lower()

                record = abbrev_index.get(lookup_key)
                if not record:
                    skipped += 1
                    skipped_names.append(f"  [{category_name}] {mol_name_str}")
                    continue

                smiles = record.get("SMILES", "")
                if not smiles:
                    skipped += 1
                    skipped_names.append(f"  [{category_name}] {mol_name_str} (no SMILES)")
                    continue

                molecules.append({
                    "name": mol_name_str,
                    "smiles": smiles,
                    "formula": record.get("Molecular formula", ""),
                    "weight": record.get("Molecular weight", 0),
                    "category": category_name,
                    "subcategory": subcat_display,
                })
                matched += 1

        subcategories[category_name] = sorted(cat_subcats)

    # Sort molecules by name for deterministic output
    molecules.sort(key=lambda m: m["name"].lower())

    categories = sorted(CATEGORY_MAP.values())

    print(f"\nMatched: {matched}, Skipped: {skipped}")
    if skipped_names:
        print("Skipped molecules:")
        for name in skipped_names:
            print(name)

    # Build JS output
    data_obj = {
        "categories": categories,
        "subcategories": subcategories,
        "molecules": molecules,
    }

    js_content = (
        "/* Auto-generated by tools/build_biomacromolecule_data.py — DO NOT EDIT */\n"
        "window.BiomacromoleculeData = "
        + json.dumps(data_obj, indent=1, ensure_ascii=False)
        + ";\n"
    )

    os.makedirs(os.path.dirname(OUTPUT_JS), exist_ok=True)
    with open(OUTPUT_JS, "w") as fh:
        fh.write(js_content)

    file_size = os.path.getsize(OUTPUT_JS)
    print(f"\nWrote {OUTPUT_JS}")
    print(f"  {matched} molecules, {file_size / 1024:.1f} KB")
    print(f"  Categories: {categories}")
    for cat, subs in sorted(subcategories.items()):
        print(f"  {cat}: {subs}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
